### PR TITLE
Extract rfc1951

### PR DESCRIPTION
**Pull request by dinosaure**
cc @cfcs

### CODE REVIEW

**Comment by dinosaure** [comment]
From my note, this PR includes:
- a factorization of basics input/output operations (to avoid redundant code, and prone errors)
- a little optimization when we inflate a dictionary (avoid a double check of how many bits we have)
- an _un-curryification_ of `window`, in fact, it's better to move this variable in `t` (as a part of state) than to pass it as an argument to all functions

This PR extracts only RFC1951 to __inflate__ (deflate algorithm continue to produce a `zlib` stream).

**Comment by dinosaure** [comment]
I will run a fuzzer on this PR in my server and do a snapshot then.

**Comment by dinosaure** [comment]
Ok, I will start a new fuzzer and fix a bug with a random input to _inflate_. Then, make a release and move on.

**Comment by cfcs** [comment]
Thank you for this work!

**Comment by dinosaure** [comment]
Of course, `afl` result:

afl-fuzz

**Comment by cfcs** [comment]
@dinosaure is the afl result missing?

**Comment by dinosaure** [comment]
Currently, `afl-fuzz` did not catch any bugs on `zlib` implementation. I just want to make a release without any regression (specially to not break `ocaml-git` by this way) - I clearly don't want to look `hexdump` of PACK file again. Then, I need to implement a fuzzer only on RFC1951, however, I can not compare with a C implementation (or I need to make a new library which binds RFC1951 on the OCaml world). Then, the final goal is to split RFC1951 and zlib on interface and provide 2 `opam` package :) !

PS: I currently look about infinite loop. As I said, first case is about `refiller` where `read` returns `0`, so in a context where we process a file, we expect more input and have a partial inflated file. So in top of the `refiller`, we need to raise an `End_of_file` exception. But it's out the scope of Decompress (good news).

However, as I said, I get with a random input an infinite loop I need to know precisely why. So, it's about documentation to explain behavior of `refiller` and a serious bug on implementation.

**Comment by cfcs** [comment]
Again, thanks for doing this work!

**Pull request merged**
