### PR TITLE
First shot about a new Lz77 algorithm

### LINKED ISSUE #104: Compression support
The current implementation of the `GZIP` interface exposes a `compress` function. However, the encoder does not handle any compression level (see `Gz.Def.encoder` interface documentation).

Is it planned to fully implement compression features through this library?

### PR DESCRIPTION
**Pull request by dinosaure**
It's a new implementation of the Lz77 algorithm. This rewrite updates a bit the interface (where the needed _window_ is larger than before - to be able to _lookup_). I will do some benchmarks. This PR wants to fix #104.

### CODE REVIEW

**Comment by dinosaure** [comment]
Performances with `lzbench` from `master`:
```sh
lzbench 1.8 (64-bit Linux)   Assembled by P.Skibinski
Compressor name         Compress. Decompress. Compr. size  Ratio Filename
memcpy                  12621 MB/s 14789 MB/s      377109 100.00 news
decompress dev -3          21 MB/s    74 MB/s      292951  77.68 news
zlib 1.2.11 -4             32 MB/s   198 MB/s      149282  39.59 news
blosclz 2.0.0 -6          188 MB/s   515 MB/s      297866  78.99 news
done... (cIters=1 dIters=1 cTime=1.0 dTime=2.0 chunkSize=1706MB cSpeed=0MB)
```

```sh
lzbench 1.8 (64-bit Linux)   Assembled by P.Skibinski
Compressor name         Compress. Decompress. Compr. size  Ratio Filename
memcpy                  11988 MB/s 14841 MB/s      513216 100.00 pic
decompress dev -3          68 MB/s   200 MB/s       85384  16.64 pic
zlib 1.2.11 -4             73 MB/s   377 MB/s       58457  11.39 pic
blosclz 2.0.0 -6          506 MB/s  1427 MB/s      114427  22.30 pic
done... (cIters=1 dIters=1 cTime=1.0 dTime=2.0 chunkSize=1706MB cSpeed=0MB)
```

Performances with `lzbench` from this PR:
```sh
lzbench 1.8 (64-bit Linux)   Assembled by P.Skibinski
Compressor name         Compress. Decompress. Compr. size  Ratio Filename
memcpy                  12507 MB/s 14737 MB/s      377109 100.00 news
decompress dev -3        9.65 MB/s    74 MB/s      168451  44.67 news
zlib 1.2.11 -4             32 MB/s   199 MB/s      149282  39.59 news
blosclz 2.0.0 -6          187 MB/s   514 MB/s      297866  78.99 news
done... (cIters=1 dIters=1 cTime=1.0 dTime=2.0 chunkSize=1706MB cSpeed=0MB)
```

```sh
lzbench 1.8 (64-bit Linux)   Assembled by P.Skibinski
Compressor name         Compress. Decompress. Compr. size  Ratio Filename
memcpy                  12235 MB/s 14632 MB/s      513216 100.00 pic
decompress dev -3          20 MB/s   214 MB/s       67532  13.16 pic
zlib 1.2.11 -4             74 MB/s   377 MB/s       58457  11.39 pic
blosclz 2.0.0 -6          507 MB/s  1428 MB/s      114427  22.30 pic
done... (cIters=1 dIters=1 cTime=1.0 dTime=2.0 chunkSize=1706MB cSpeed=0MB)
```

Conclusion, the compression ratio is definitely better about `news` (77.68 % versus 44.67 %) and `pic` (13.16 % versus 16.64 %). However, we have an impact on performances:
- `news` (21 MB/s versus 9.65 MB/s)
- `pic` (68 MB/s versus 20 MB/s)

Currently, I implemented only one algorithm (with one level of compression). I missed 3 others implementations:
- [ ] `deflate_fast` (better performances but worse ratio)
- [ ] `deflate_stored` (may be better performances - no huffman compression - and better ratio - depends on frequencies)
- [ ] `deflate_rle`simple RLE compression (may be better for corpus such as `pico`)

**Comment by dinosaure** [comment]
A bug was discovered and fixed with 3e70460. It's time to relaunch benchmarks.

**Comment by dinosaure** [comment]
```sh
dinosaure@turbine:~/dev/lzbench$ ./lzbench -edecompress,4,5,6,7/zlib,4,5,6,7 news
lzbench 1.8 (64-bit Linux)   Assembled by P.Skibinski
Compressor name         Compress. Decompress. Compr. size  Ratio Filename
memcpy                  12235 MB/s 14854 MB/s      377109 100.00 news
decompress dev -4          13 MB/s    71 MB/s      174833  46.36 news
decompress dev -5          10 MB/s    73 MB/s      169381  44.92 news
decompress dev -6        9.54 MB/s    74 MB/s      168451  44.67 news
decompress dev -7        9.04 MB/s    74 MB/s      168283  44.62 news
zlib 1.2.11 -4             32 MB/s   199 MB/s      149282  39.59 news
zlib 1.2.11 -5             22 MB/s   197 MB/s      145483  38.58 news
zlib 1.2.11 -6             18 MB/s   198 MB/s      144800  38.40 news
zlib 1.2.11 -7             17 MB/s   198 MB/s      144648  38.36 news
done... (cIters=1 dIters=1 cTime=1.0 dTime=2.0 chunkSize=1706MB cSpeed=0MB)
dinosaure@turbine:~/dev/lzbench$ ./lzbench -edecompress,4,5,6,7/zlib,4,5,6,7 pic
lzbench 1.8 (64-bit Linux)   Assembled by P.Skibinski
Compressor name         Compress. Decompress. Compr. size  Ratio Filename
memcpy                  12199 MB/s 14630 MB/s      513216 100.00 pic
decompress dev -4          31 MB/s   206 MB/s       70467  13.73 pic
decompress dev -5          27 MB/s   211 MB/s       68926  13.43 pic
decompress dev -6          20 MB/s   215 MB/s       67532  13.16 pic
decompress dev -7          17 MB/s   219 MB/s       66497  12.96 pic
zlib 1.2.11 -4             73 MB/s   377 MB/s       58457  11.39 pic
zlib 1.2.11 -5             58 MB/s   388 MB/s       57416  11.19 pic
zlib 1.2.11 -6             37 MB/s   406 MB/s       56465  11.00 pic
zlib 1.2.11 -7             30 MB/s   419 MB/s       55364  10.79 pic
done... (cIters=1 dIters=1 cTime=1.0 dTime=2.0 chunkSize=1706MB cSpeed=0MB)
dinosaure@turbine:~/dev/lzbench$ ./lzbench -edecompress,4,5,6,7/zlib,4,5,6,7 book2 
lzbench 1.8 (64-bit Linux)   Assembled by P.Skibinski
Compressor name         Compress. Decompress. Compr. size  Ratio Filename
memcpy                  12236 MB/s 14820 MB/s      610856 100.00 book2
decompress dev -4          15 MB/s    76 MB/s      259394  42.46 book2
decompress dev -5          11 MB/s    78 MB/s      247353  40.49 book2
decompress dev -6        8.59 MB/s    80 MB/s      243925  39.93 book2
decompress dev -7        7.95 MB/s    80 MB/s      243460  39.86 book2
zlib 1.2.11 -4             35 MB/s   220 MB/s      217629  35.63 book2
zlib 1.2.11 -5             23 MB/s   220 MB/s      209368  34.27 book2
zlib 1.2.11 -6             16 MB/s   225 MB/s      206664  33.83 book2
zlib 1.2.11 -7             14 MB/s   225 MB/s      206311  33.77 book2
done... (cIters=1 dIters=1 cTime=1.0 dTime=2.0 chunkSize=1706MB cSpeed=0MB)
dinosaure@turbine:~/dev/lzbench$ 
```

We have plus and less the same **magnitude** than `zlib` about performances and ratio. Which is a good news. We can see a _small_ improvement comparing to our last benchmark:
- with `pic`, `decompress ~level:{4,5,6}` has a better performance (and the same ratio, ~ 13.5) than before. Indeed, we are able to _tune_ the Lz77 algorithm with some parameters and it seems that `decompress ~level:4`, even if it has a worse radio (13.73 versus 13.16), it beats the old version of 10Mb/s (which is pretty good)
- we have the same result with `news` (9.65 MB/s versus 13 MB/s) with a not-so-bad ratio
- I added `book2` to show up that performances are intrinsic with the corpus

However, `zlib` is able to compress more corpus with same level. It's hard to know at this stage why when the Lz77 is exactly the same: may be it's about the huffman tree and the way to encode it.

The next step will be `deflate_fast` (level 1, 2 & 3).

**Comment by dinosaure** [comment]
```sh
dinosaure@turbine:~/dev/lzbench$ ./lzbench -edecompress,1,2,3,4/zlib,1,2,3,4 book2 
lzbench 1.8 (64-bit Linux)   Assembled by P.Skibinski
Compressor name         Compress. Decompress. Compr. size  Ratio Filename
memcpy                  12033 MB/s 14992 MB/s      610856 100.00 book2
decompress dev -1          18 MB/s    59 MB/s      309782  50.71 book2
decompress dev -2          17 MB/s    60 MB/s      291687  47.75 book2
decompress dev -3          14 MB/s    66 MB/s      274291  44.90 book2
decompress dev -4          15 MB/s    76 MB/s      259394  42.46 book2
zlib 1.2.11 -1             52 MB/s   210 MB/s      248917  40.75 book2
zlib 1.2.11 -2             47 MB/s   217 MB/s      237838  38.94 book2
zlib 1.2.11 -3             35 MB/s   224 MB/s      228322  37.38 book2
zlib 1.2.11 -4             35 MB/s   220 MB/s      217629  35.63 book2
done... (cIters=1 dIters=1 cTime=1.0 dTime=2.0 chunkSize=1706MB cSpeed=0MB)
dinosaure@turbine:~/dev/lzbench$ ./lzbench -edecompress,1,2,3,4/zlib,1,2,3,4 news
lzbench 1.8 (64-bit Linux)   Assembled by P.Skibinski
Compressor name         Compress. Decompress. Compr. size  Ratio Filename
memcpy                  12314 MB/s 14863 MB/s      377109 100.00 news
decompress dev -1          17 MB/s    59 MB/s      197871  52.47 news
decompress dev -2          16 MB/s    66 MB/s      208594  55.31 news
decompress dev -3          13 MB/s    68 MB/s      202032  53.57 news
decompress dev -4          13 MB/s    71 MB/s      174833  46.36 news
zlib 1.2.11 -1             48 MB/s   198 MB/s      164288  43.57 news
zlib 1.2.11 -2             43 MB/s   202 MB/s      159181  42.21 news
zlib 1.2.11 -3             35 MB/s   205 MB/s      155392  41.21 news
zlib 1.2.11 -4             32 MB/s   198 MB/s      149282  39.59 news
done... (cIters=1 dIters=1 cTime=1.0 dTime=2.0 chunkSize=1706MB cSpeed=0MB)
dinosaure@turbine:~/dev/lzbench$ ./lzbench -edecompress,1,2,3,4/zlib,1,2,3,4 pic
lzbench 1.8 (64-bit Linux)   Assembled by P.Skibinski
Compressor name         Compress. Decompress. Compr. size  Ratio Filename
memcpy                  12221 MB/s 14633 MB/s      513216 100.00 pic
decompress dev -1          48 MB/s   193 MB/s       86953  16.94 pic
decompress dev -2          45 MB/s   197 MB/s       84154  16.40 pic
decompress dev -3          39 MB/s   204 MB/s       80486  15.68 pic
decompress dev -4          31 MB/s   205 MB/s       70467  13.73 pic
zlib 1.2.11 -1            115 MB/s   417 MB/s       65559  12.77 pic
zlib 1.2.11 -2            107 MB/s   426 MB/s       63897  12.45 pic
zlib 1.2.11 -3             88 MB/s   445 MB/s       62521  12.18 pic
zlib 1.2.11 -4             74 MB/s   377 MB/s       58457  11.39 pic
done... (cIters=1 dIters=1 cTime=1.0 dTime=2.0 chunkSize=1706MB cSpeed=0MB)
dinosaure@turbine:~/dev/lzbench$ 
```

`decompress ~level:{1,2,3}` is `deflate_fast`. As we can see, `deflate_fast` is faster than `deflate_slow` - and not only because it has a different name... I think the PR is good enough to merge it and cut a release.

About `deflate_stored` and some others optimizations.
We decided to choose an other design than `zlib` which is a black-box about several aspects of RFC1951. `decompress` as is allows the user to tweak on these details such as:
- use the fixed huffman tree (and missing the deflation of the dynamic huffman tree)
- use the flat block (as `deflate_stored`)

Such parameters needs more than a simple level so I need to figure out the proper API about that but these choices are available for the end user if he wants.

About `deflate_rle`, it's an RLE compression which is not available as is in `zlib` only if the user compiles `zlib` with some specific macros. So I'm not interested to implement it.

**Comment by dinosaure** [comment]
@vectr0r-vicall what do you think about that? Now, you have the ability to choose one level between `0` and `9`.

**Comment by dinosaure** [comment]
**NOTE**: no regression on `ocaml-git` and generated PACK file are smaller than before :tada:.

**Comment by dinosaure** [comment]
I think it's ready to merge, the release of it will waiting a feedback from @vect0r-vicall and the @clecat's works.

**Comment by vect0r-vicall** [comment]
> @vect0r-vicall what do you think about that? Now, you have the ability to choose one level between `0` and `9`.

Good news! Thanks. I'll take a look soon and I'll give you some feedback.

**Comment by dinosaure** [comment]
Note that the API changes a bit. The `window` needed to compress has a new type - it's not shared anymore between the compressor and the decompressor. The fact is: the `window` needed for the compression is 2-times larger than before (to have an opportunity to lookup and find _matches_).

As I said, you have several ways to "customize" the compression. Currently only 3 parameters exists:
- the level (`0 .. 9`)
- the window (the size of it)
- the huffman tree used

### The level

As `zlib`, we provide 9 levels which determine 2 things:
- which internal configuration we want to use
- which algorithm (`deflate_fast` or `deflate_slow`) we want to use

Of course, it depends on your corpus. As you can see, `pic` (an ELF executable) has an incredible compression ratio where `news` or `book2` (human readable contents) need `deflate_slow` to have a very good compression ratio. As far as I can tell, usually, the higher level propose a better ratio (but it is slower).

### The window

The `window` is more about memory consumption than compression ratio/speed. It's sure that a smaller window has less opportunities to find a _match_. So the compression ratio is worse at the end. Usually, the window is `15` bits. You should keep that as a default argument if you don't really care about memory consumption.

Note that `decompress` has an API model which allows to use and re-use the window for the compression several times. So you are able to allocate it only one time and, as long as compression are done sequentially, you can keep the same window - for example, in our tests, we use only one and unique window for all of our tests.

### The huffman tree

Previous parameters are available at the `zlib` level: `Zl` module. However, you probably wants to use the static huffman-tree instead to define systematically a dynamic one. Again, it depends on your corpus. If your corpus use a smaller alphabet than `0x0 .. 0xff`, it could be interesting to use a dynamic huffman which corresponds to your alphabet. Otherwise, the static huffman tree provided by `zlib`/`decompress` can be useful. By this way, we don't encode the huffman tree and directly inflate the block.

Of course, the distribution (frequencies) of byte is arbitrary - and it does not correspond to your distribution according to your corpus. If you want to play with that, you can directly use `De` which is the lower-layer of `zlib`. Then, we can think about a better API and resolve some issues:
- how to use my own distribution and the static huffman tree block with my own distribution?
- how to enforce `Zl` to use that (partially solved with the `?dynamic` argument)

At least, this PR is a huge improvement about ratio compression. If performances really matters, it's an orthogonal question but I can spend my time on that.

**Pull request merged**
