### PR TITLE
GZip

### PR DESCRIPTION
**Pull request by dinosaure**

### CODE REVIEW

**Comment by dinosaure** [comment]
- [ ] provide an `Higher` interface as `Zl` and `De`
- [ ] write documentation
- [ ] review from another one?
- [ ] release of `checkseum`

**Comment by dinosaure** [comment]
@copy & @hcarty - this PR seems to be finished. Are you happy with the given interface?

**Comment by copy** [comment]
@dinosaure I'm happy with the interface. Just one observation, I found it surprising that `Higher.uncompress` uses exceptions, considering the general style of Mirage libraries to avoid them.

**Comment by dinosaure** [comment]
> I found it surprising that Higher.uncompress uses exceptions, considering the general style of Mirage libraries to avoid them.

So, it's orthogonal to this PR but we can open an issue and avoid leaking exception. From my case, I don't use `Higher` interface where I directly use `Inf` and `Def` - I provided `Higher` mostly for people who are not very aware about MirageOS.

So let me know if you want an update and I can provide a PR on `Gz`, `Zl` and `De` :+1:.

**Comment by copy** [comment]
> So let me know if you want an update and I can provide a PR on Gz, Zl and De +1.

That would nice, yeah.

**Pull request merged**
